---

- name: ensure backports apt repo is setup
  apt_repository: >
    repo="deb {{ backports_url }} {{ backports_distribution_release }} main"
    state=present 
    update_cache=yes
  sudo: yes

- name: ensure twisted from backports is installed
  apt: >
    pkg=python-twisted
    default_release="{{ backports_distribution_release }}"
    state=present
  sudo: yes

- name: ensure tahoe dependencies are installed
  apt:
    pkg: "{{item}}"
    state: present
  with_items: ["build-essential", "python-dev", "libffi-dev", "git", "python-openssl"]
  sudo: yes

- name: install torsocks if use_torsocks is yes
  apt:
    pkg: torsocks
    state: present
  when: use_torsocks

- name: check if tahoe-lafs is already installed
  stat: path={{ tahoe_source_dir }}
  register: tahoe_source_dir_st

# BUG: verify gpg signature in git release tag
# BUG: what happens if the git clone gets interrupted?
# Use a debian package instead! It's much better!
- name: "git clone Leif's tahoe-lafs truckee branch if directory is non-existent"
  git: repo="{{ tahoe_git_url }}"
    dest="{{ tahoe_source_dir }}"
    version="{{ tahoe_git_branch }}"
  when: tahoe_source_dir_st.stat.isdir is not defined and not use_torsocks

- name: "usewithtor git clone {{ tahoe_git_url }} {{ tahoe_source_dir }}"
  command: "usewithtor git clone {{ tahoe_git_url }} {{ tahoe_source_dir }}"
  when: tahoe_source_dir_st.stat.isdir is not defined and use_torsocks

- name: "switch to {{ tahoe_git_branch }} git branch"
  command: "chdir={{ tahoe_source_dir }} git checkout {{ tahoe_git_branch }}"
  when: tahoe_source_dir_st.stat.isdir is not defined and use_torsocks

- name: get state of tahoe_dep_tarball
  stat: path={{ tahoe_source_dir }}/{{ tahoe_dep_tarball }}
  register: tahoe_source_tarball_st

- name: ensure tahoe-lafs dependency tarball is downloaded
  get_url: >
    url={{ tahoe_dep_tarball_url }}
    dest={{ tahoe_source_dir }}/{{ tahoe_dep_tarball }}
    mode=0440
    validate_certs=yes
    sha256sum={{ tahoe_dep_tarball_sha256sum }}
  when: not tahoe_source_tarball_st.stat.exists and not use_torsocks

- name: usewithtor wget {{ tahoe_dep_tarball_url }}
  command: usewithtor wget -O {{ tahoe_source_dir }}/{{ tahoe_dep_tarball }} {{ tahoe_dep_tarball_url }}
  when: not tahoe_source_tarball_st.stat.exists and use_torsocks

- name: tarball checksum comparison
  shell: "sha256sum {{ tahoe_source_dir }}/{{ tahoe_dep_tarball }} | cut -d ' ' -f 1"
  register: dep_tarball_sha256sum

- debug: msg="{{ dep_tarball_sha256sum.stdout }}"

- name: assert that the tahoe dependency tarball is sha256sum verified
  assert:
    that: "dep_tarball_sha256sum.stdout == tahoe_dep_tarball_sha256sum"

- name: get state of tahoe-deps directory
  stat: path={{ tahoe_source_dir }}/tahoe-deps
  register: tahoe_deps_dir_st

# BUG: what if the tar extraction gets interrupted?
# bad news bears; use Debian package instead!
- name: extract tahoe-deps tarball if directory does not exist
  command: tar xf {{ tahoe_source_dir }}/{{ tahoe_dep_tarball }} --directory {{ tahoe_source_dir }}
  when: tahoe_deps_dir_st.stat.isdir is not defined

- name: build tahoe-lafs
  shell: chdir={{ tahoe_source_dir }} http_proxy=localhost:0 https_proxy=localhost:0 python setup.py build

