---
- hosts: onion-introducer-storage
  vars:
    hidden_services_parent_dir: "/var/lib/tor/services"
    introducer_node_name: "IntroducerNode"
    introducer_tub_port: "33000"
    introducer_web_port: "33001"
    storage_service_name: "storage"
    storage_tub_port: "34000"
    storage_web_port: "34001"
    hidden_services: [
      { dir: "intro-web", ports: [{ virtport: "{{ introducer_web_port }}", target: "127.0.0.1:{{ introducer_web_port }}" }] },
      { dir: "introducer", ports: [{ virtport: "{{ introducer_tub_port }}", target: "127.0.0.1:{{ introducer_tub_port }}" }] },
      { dir: "storage-web", ports: [{ virtport: "{{ storage_web_port }}", target: "127.0.0.1:{{ storage_web_port }}" }] },
      { dir: "storage", ports: [{ virtport: "{{ storage_tub_port }}", target: "127.0.0.1:{{ storage_tub_port }}" }] },
    ]
  roles:
    - { role: ansible-tor,
        tor_wait_for_hidden_services: yes,
        tor_distribution_release: "wheezy",
        tor_ExitPolicy: "reject *:*",
        tor_hidden_services: "{{ hidden_services }}",
        tor_hidden_services_parent_dir: "{{ hidden_services_parent_dir }}",
        sudo: yes
      }
    - { role: ansible-tahoe-lafs,
        tahoe_introducer: yes,
        tahoe_local_introducers_dir: "/home/amnesia/Persistent/projects/ansible-base/tahoe-lafs_introducers",
        use_torsocks: yes,
        tahoe_hidden_service_name: "introducer",
        tor_hidden_services_parent_dir: "{{ hidden_services_parent_dir }}",
        tahoe_introducer_port: "{{ introducer_tub_port }}",
        tahoe_web_port: "{{ introducer_web_port }}",
        tahoe_tub_port: "{{ introducer_tub_port }}",
        tahoe_shares_needed: 2,
        tahoe_shares_happy: 3,
        tahoe_shares_total: 4,
        backports_url: "http://ftp.de.debian.org/debian/",
        backports_distribution_release: "wheezy-backports",
        tahoe_source_dir: "/home/human/tahoe-lafs-src",
        tahoe_run_dir: "/home/human/tahoe_introducer"
      }
    - { role: ansible-tahoe-lafs,
        tahoe_local_introducers_dir: "/home/amnesia/Persistent/projects/ansible-base/tahoe-lafs_introducers",
        tahoe_storage_enabled: "true",
        tahoe_hidden_service_name: "storage",
        tor_hidden_services_parent_dir: "{{ hidden_services_parent_dir }}",
        tahoe_web_port: "{{ storage_web_port }}",
        tahoe_tub_port: "{{ storage_tub_port }}",
        tahoe_shares_needed: 2,
        tahoe_shares_happy: 3,
        tahoe_shares_total: 4,
        backports_url: "http://ftp.de.debian.org/debian/",
        backports_distribution_release: "wheezy-backports",
        tahoe_source_dir: "/home/human/tahoe-lafs-src",
        tahoe_run_dir: "/home/human/tahoe_storage"
      }
